name: Check IPv6

on:
  schedule:
    - cron: '22 22 1 1 *'
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Enable IPv6
      run: |
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
        sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0
        sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
            
    - name: Install requests
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run check_v6.py
      run: |
        python check_v6.py

    - name: Commit cs.txt
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add cs.txt
        git commit -m "Update cs.txt" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
