name: Check IPv6

on:
  schedule:
    - cron: '22 22 1 1 *'
  workflow_dispatch:
    branches:
      - main

jobs:
  check-ipv6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run IPv6 check
        run: python check_v6.py

      - name: Upload online.txt
        uses: actions/upload-artifact@v2
        with:
          name: cs-urls
          path: cs.txt
